import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/layout/Navbar";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
   return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col">

        <Navbar />

        {children}

      </body>

    </html>
  );
}
